// TypeScript types for collection data
export interface CollectionItem {
  id: number;
  collection: string;
  designNo: number;
  color: string;
  // sizeCm: string;
  quality: string;
  contents: string;
  stockRef: string;
  madeIn: string;
  notes: string;
  imageSrc: string;
}

// Collection data
export const collectionsData: CollectionItem[] = [
  {
    "id": 2,
    "collection": "Eira",
    "designNo": 201,
    "color": "Canary",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.201",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/002_eira_canary.jpg"
  },
  {
    "id": 3,
    "collection": "Eira",
    "designNo": 201,
    "color": "Espresso",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.201",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/003_eira_espresso.jpg"
  },
  {
    "id": 4,
    "collection": "Eira",
    "designNo": 201,
    "color": "Nordic Pine ARS 1I16",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.201",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/004_eira_nordic-pine-ars-1i16.jpg"
  },
  {
    "id": 5,
    "collection": "Eira",
    "designNo": 201,
    "color": "Nordic Sky ARS 2m-11",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.201",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/005_eira_nordic-sky-ars-2m-11.jpg"
  },
  {
    "id": 6,
    "collection": "Eira",
    "designNo": 201,
    "color": "Walnut",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.201",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/006_eira_walnut.jpg"
  },
  {
    "id": 7,
    "collection": "Eira",
    "designNo": 201,
    "color": "Mauve",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.201",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/007_eira_mauve.jpg"
  },
  {
    "id": 8,
    "collection": "Eira",
    "designNo": 201,
    "color": "Nordic Forest 1HI16",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.201",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/008_eira_nordic-forest-1hi16.jpg"
  },
  {
    "id": 9,
    "collection": "Eira",
    "designNo": 201,
    "color": "Sage Mist",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.201",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/009_eira_sage-mist.jpg"
  },
  {
    "id": 10,
    "collection": "Eira",
    "designNo": 201,
    "color": "Deep Fjord",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.201",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/010_eira_deep-fjord.jpg"
  },
  {
    "id": 11,
    "collection": "Eira",
    "designNo": 201,
    "color": "Navy",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.201",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/011_eira_navy.jpg"
  },
  {
    "id": 12,
    "collection": "Eira",
    "designNo": 201,
    "color": "Dusty Rose",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.201",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/012_eira_dusty-rose.jpg"
  },
  {
    "id": 13,
    "collection": "Eira",
    "designNo": 201,
    "color": "Dark Taupe",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.201",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/013_eira_dark-taupe.jpg"
  },
  {
    "id": 14,
    "collection": "Eira",
    "designNo": 201,
    "color": "Light Taupe",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.201",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/014_eira_light-taupe.jpg"
  },
  {
    "id": 15,
    "collection": "Eira",
    "designNo": 201,
    "color": "Brown",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.201",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/015_eira_brown.jpg"
  },
  {
    "id": 16,
    "collection": "Eira",
    "designNo": 201,
    "color": "Mushroom",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.201",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/016_eira_mushroom.jpg"
  },
  {
    "id": 17,
    "collection": "Eira",
    "designNo": 201,
    "color": "White",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.201",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/017_eira_white.jpg"
  },
  {
    "id": 18,
    "collection": "Astra",
    "designNo": 210,
    "color": "Sand 4M15/G011",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Wool & Tencel & 20% Cotton",
    "stockRef": "ID.210",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/018_astra_sand-4m15-g011.jpg"
  },
  {
    "id": 19,
    "collection": "Astra",
    "designNo": 210,
    "color": "Taupe Gray IB20/D106",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Wool & Tencel & 20% Cotton",
    "stockRef": "ID.210",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/019_astra_taupe-gray-ib20-d106.jpg"
  },
  {
    "id": 20,
    "collection": "Astra",
    "designNo": 210,
    "color": "Royal Blue 2J17/J126",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Wool & Tencel & 20% Cotton",
    "stockRef": "ID.210",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/020_astra_royal-blue-2j17-j126.jpg"
  },
  {
    "id": 21,
    "collection": "Astra",
    "designNo": 210,
    "color": "Moss 3C06/A051",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Wool & Tencel & 20% Cotton",
    "stockRef": "ID.210",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/021_astra_moss-3c06-a051.jpg"
  },
  {
    "id": 22,
    "collection": "Astra",
    "designNo": 210,
    "color": "Rust 2D01/Aoo4",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Wool & Tencel & 20% Cotton",
    "stockRef": "ID.210",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/022_astra_rust-2d01-aoo4.jpg"
  },
  {
    "id": 23,
    "collection": "Astra",
    "designNo": 210,
    "color": "Golden Brown AH05/A114",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Wool & Tencel & 20% Cotton",
    "stockRef": "ID.210",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/023_astra_golden-brown-ah05-a114.jpg"
  },
  {
    "id": 24,
    "collection": "Elara",
    "designNo": 211,
    "color": "Snow White",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Wool & Tencel & 20% Cotton",
    "stockRef": "ID.211",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/024_elara_snow-white.jpg"
  },
  {
    "id": 25,
    "collection": "Elara",
    "designNo": 211,
    "color": "Spring Green",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Wool & Tencel & 20% Cotton",
    "stockRef": "ID.211",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/025_elara_spring-green.jpg"
  },
  {
    "id": 26,
    "collection": "Elara",
    "designNo": 211,
    "color": "Rust & Silver",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Wool & Tencel & 20% Cotton",
    "stockRef": "ID.211",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/026_elara_rust-and-silver.jpg"
  },
  {
    "id": 27,
    "collection": "Elara",
    "designNo": 211,
    "color": "Sand",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Wool & Tencel & 20% Cotton",
    "stockRef": "ID.211",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/027_elara_sand.jpg"
  },
  {
    "id": 28,
    "collection": "Elara",
    "designNo": 211,
    "color": "Espresso Taupe",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Wool & Tencel & 20% Cotton",
    "stockRef": "ID.211",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/028_elara_espresso-taupe.jpg"
  },
  {
    "id": 29,
    "collection": "Elara",
    "designNo": 211,
    "color": "Slate",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Wool & Tencel & 20% Cotton",
    "stockRef": "ID.211",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/029_elara_slate.jpg"
  },
  {
    "id": 30,
    "collection": "Elara",
    "designNo": 211,
    "color": "Gray",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Wool & Tencel & 20% Cotton",
    "stockRef": "ID.211",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/030_elara_gray.jpg"
  },
  {
    "id": 31,
    "collection": "Elara",
    "designNo": 211,
    "color": "Sage",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Wool & Tencel & 20% Cotton",
    "stockRef": "ID.211",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/031_elara_sage.jpg"
  },
  {
    "id": 32,
    "collection": "Strata",
    "designNo": 206,
    "color": "White & Jute",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Jute & Tencel",
    "stockRef": "CL.206",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/032_strata_white-and-jute.jpg"
  },
  {
    "id": 33,
    "collection": "Strata",
    "designNo": 206,
    "color": "Cocoa & Jute",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Jute & Tencel",
    "stockRef": "CL.206",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/033_strata_cocoa-and-jute.jpg"
  },
  {
    "id": 34,
    "collection": "Strata",
    "designNo": 206,
    "color": "Burgundy & Jute",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Jute & Tencel",
    "stockRef": "CL.206",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/034_strata_burgundy-and-jute.jpg"
  },
  {
    "id": 35,
    "collection": "Strata",
    "designNo": 206,
    "color": "Warm Sand & Jute",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Jute & Tencel",
    "stockRef": "CL.206",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/035_strata_warm-sand-and-jute.jpg"
  },
  {
    "id": 36,
    "collection": "Strata",
    "designNo": 205,
    "color": "Rust & Jute ARS H011",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Jute & Tencel",
    "stockRef": "CL.201",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/036_strata_rust-and-jute-ars-h011.jpg"
  },
  {
    "id": 37,
    "collection": "Niva",
    "designNo": 202,
    "color": "Oat & Linen",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "Wool & Linen",
    "stockRef": "JA.202",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/037_niva_oat-and-linen.jpg"
  },
  {
    "id": 38,
    "collection": "Fen",
    "designNo": 214,
    "color": "Olive Brown",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "IR.214",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/038_fen_olive-brown.jpg"
  },
  {
    "id": 39,
    "collection": "Fen",
    "designNo": 214,
    "color": "Rose",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "IR.214",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/039_fen_rose.jpg"
  },
  {
    "id": 40,
    "collection": "Fen",
    "designNo": 214,
    "color": "Navy Blue",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "IR.214",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/040_fen_navy-blue.jpg"
  },
  {
    "id": 41,
    "collection": "Fen",
    "designNo": 214,
    "color": "Gray",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "IR.214",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/041_fen_gray.jpg"
  },
  {
    "id": 42,
    "collection": "Fjord Line",
    "designNo": 102,
    "color": "Snow & Moss",
    "quality": "Flat Woven",
    "contents": "100% Wool",
    "stockRef": "JA.102",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/042_fjord-line_snow-and-moss.jpg"
  },
  {
    "id": 43,
    "collection": "Fjord Line",
    "designNo": 102,
    "color": "Rust & Ivory",
    "quality": "Flat Woven",
    "contents": "100% Wool",
    "stockRef": "JA.103",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/043_fjord-line_rust-and-ivory.jpg"
  },
  {
    "id": 44,
    "collection": "Fjord Line",
    "designNo": 102,
    "color": "Cocoa & Ivory",
    "quality": "Flat Woven",
    "contents": "100% Wool",
    "stockRef": "JA.104",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/044_fjord-line_cocoa-and-ivory.jpg"
  },
  {
    "id": 45,
    "collection": "Fjord Line",
    "designNo": 102,
    "color": "Sun & Snow",
    "quality": "Flat Woven",
    "contents": "100% Wool",
    "stockRef": "JA.105",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/045_fjord-line_sun-and-snow.jpg"
  },
  {
    "id": 46,
    "collection": "Fjord Line",
    "designNo": 102,
    "color": "Ink & Snow",
    "quality": "Flat Woven",
    "contents": "100% Wool",
    "stockRef": "JA.106",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/046_fjord-line_ink-and-snow.jpg"
  },
  {
    "id": 47,
    "collection": "Fjord Line",
    "designNo": 102,
    "color": "Charcoal Gray & Ivory",
    "quality": "Flat Woven",
    "contents": "100% Wool",
    "stockRef": "JA.107",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/047_fjord-line_charcoal-gray-and-ivory.jpg"
  },
  {
    "id": 48,
    "collection": "Dota",
    "designNo": 104,
    "color": "Sand",
    "quality": "Flat Woven",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.104",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/048_dota_sand.jpg"
  },
  {
    "id": 49,
    "collection": "Dota",
    "designNo": 104,
    "color": "Sage",
    "quality": "Flat Woven",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.104",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/049_dota_sage.jpg"
  },
  {
    "id": 50,
    "collection": "Dota",
    "designNo": 104,
    "color": "Walnut & Ivory",
    "quality": "Flat Woven",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.104",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/050_dota_walnut-and-ivory.jpg"
  },
  {
    "id": 51,
    "collection": "Dota",
    "designNo": 104,
    "color": "Rose",
    "quality": "Flat Woven",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.104",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/051_dota_rose.jpg"
  },
  {
    "id": 52,
    "collection": "Nordic Outdoor",
    "designNo": 111,
    "color": "Walnut",
    "quality": "Flat Woven",
    "contents": "100% Recycled PET Yarn",
    "stockRef": "MC.111",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/052_nordic-outdoor_walnut.jpg"
  },
  {
    "id": 53,
    "collection": "Nordic Outdoor",
    "designNo": 111,
    "color": "Pearl White",
    "quality": "Flat Woven",
    "contents": "100% Recycled PET Yarn",
    "stockRef": "MC.111",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/053_nordic-outdoor_pearl-white.jpg"
  },
  {
    "id": 54,
    "collection": "Nordic Outdoor",
    "designNo": 111,
    "color": "Sage",
    "quality": "Flat Woven",
    "contents": "100% Recycled PET Yarn",
    "stockRef": "MC.111",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/054_nordic-outdoor_sage.jpg"
  },
  {
    "id": 55,
    "collection": "Luma Optional Fringes",
    "designNo": 101,
    "color": "Rust Red",
    "quality": "Flat Woven",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.101",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/055_luma-optional-fringes_rust-red.jpg"
  },
  {
    "id": 56,
    "collection": "Luma Optional Fringes",
    "designNo": 101,
    "color": "Terracotta",
    "quality": "Flat Woven",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.101",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/056_luma-optional-fringes_terracotta.jpg"
  },
  {
    "id": 57,
    "collection": "Luma Optional Fringes",
    "designNo": 101,
    "color": "Warm Ivory",
    "quality": "Flat Woven",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.101",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/057_luma-optional-fringes_warm-ivory.jpg"
  },
  {
    "id": 58,
    "collection": "Moonstone",
    "designNo": 203,
    "color": "Pearl & Mocha",
    "quality": "Hand Tufted",
    "contents": "Wool & Tencil",
    "stockRef": "KE.203",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/058_moonstone_pearl-and-mocha.jpg"
  },
  {
    "id": 59,
    "collection": "Root",
    "designNo": 301,
    "color": "Camel",
    "quality": "Hand Knotted, 60 Knots",
    "contents": "100% Jute",
    "stockRef": "AN.301",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/059_root_camel.jpg"
  },
  {
    "id": 60,
    "collection": "Root",
    "designNo": 301,
    "color": "Mocha & Latte",
    "quality": "Hand Knotted, 60 Knots",
    "contents": "100% Jute",
    "stockRef": "AN.301",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/060_root_mocha-and-latte.jpg"
  },
  {
    "id": 61,
    "collection": "Root",
    "designNo": 301,
    "color": "Oat",
    "quality": "Hand Knotted, 60 Knots",
    "contents": "100% Jute",
    "stockRef": "AN.301",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/061_root_oat.jpg"
  },
  {
    "id": 62,
    "collection": "Root",
    "designNo": 301,
    "color": "Charcoal & Ivory",
    "quality": "Hand Knotted, 60 Knots",
    "contents": "100% Jute",
    "stockRef": "AN.301",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/062_root_charcoal-and-ivory.jpg"
  },
  {
    "id": 63,
    "collection": "Root",
    "designNo": 301,
    "color": "Sand & Cerise",
    "quality": "Hand Knotted, 60 Knots",
    "contents": "100% Jute",
    "stockRef": "AN.301",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/063_root_sand-and-cerise.jpg"
  },
  {
    "id": 64,
    "collection": "Root",
    "designNo": 301,
    "color": "Wine & Walnut",
    "quality": "Hand Knotted, 60 Knots",
    "contents": "100% Jute",
    "stockRef": "AN.301",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/064_root_wine-and-walnut.jpg"
  },
  {
    "id": 65,
    "collection": "Root",
    "designNo": 301,
    "color": "Greige",
    "quality": "Hand Knotted, 60 Knots",
    "contents": "100% Jute",
    "stockRef": "AN.301",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/065_root_greige.jpg"
  },
  {
    "id": 66,
    "collection": "Root",
    "designNo": 301,
    "color": "Golden Flax",
    "quality": "Hand Knotted, 60 Knots",
    "contents": "100% Jute",
    "stockRef": "AN.301",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/066_root_golden-flax.jpg"
  },
  {
    "id": 67,
    "collection": "Terra Optional Fringes",
    "designNo": 103,
    "color": "Snow",
    "quality": "Flat Woven",
    "contents": "Jute",
    "stockRef": "MC.103",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/067_terra-optional-fringes_snow.jpg"
  },
  {
    "id": 68,
    "collection": "Terra Optional Fringes",
    "designNo": 103,
    "color": "Jute & Ivory",
    "quality": "Flat Woven",
    "contents": "Jute",
    "stockRef": "MC.103",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/068_terra-optional-fringes_jute-and-ivory.jpg"
  },
  {
    "id": 69,
    "collection": "Terra Optional Fringes",
    "designNo": 103,
    "color": "Ocean Blue",
    "quality": "Flat Woven",
    "contents": "Jute",
    "stockRef": "MC.103",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/069_terra-optional-fringes_ocean-blue.jpg"
  },
  {
    "id": 70,
    "collection": "Terra Optional Fringes",
    "designNo": 103,
    "color": "Marine",
    "quality": "Flat Woven",
    "contents": "Jute",
    "stockRef": "MC.103",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/070_terra-optional-fringes_marine.jpg"
  },
  {
    "id": 71,
    "collection": "Terra Optional Fringes",
    "designNo": 103,
    "color": "Walnut & Olive",
    "quality": "Flat Woven",
    "contents": "Jute",
    "stockRef": "MC.310",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/071_terra-optional-fringes_walnut-and-olive.jpg"
  },
  {
    "id": 72,
    "collection": "Grid",
    "designNo": 401,
    "color": "Black, Ivory & Gold Dust",
    "quality": "Hand Tufted",
    "contents": "Wool & Cotton",
    "stockRef": "KE.401",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/072_grid_black-ivory-and-gold-dust.jpg"
  },
  {
    "id": 73,
    "collection": "Grid",
    "designNo": 401,
    "color": "Champagne & Golden Dust",
    "quality": "Hand Tufted",
    "contents": "Wool & Cotton",
    "stockRef": "KE.401",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/073_grid_champagne-and-golden-dust.jpg"
  },
  {
    "id": 74,
    "collection": "Alda",
    "designNo": 205,
    "color": "Charcoal",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.205",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/074_alda_charcoal.jpg"
  },
  {
    "id": 75,
    "collection": "Alda",
    "designNo": 205,
    "color": "Ocean",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.205",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/075_alda_ocean.jpg"
  },
  {
    "id": 76,
    "collection": "Alda",
    "designNo": 205,
    "color": "Forest Mist",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.205",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/076_alda_forest-mist.jpg"
  },
  {
    "id": 77,
    "collection": "Alda",
    "designNo": 205,
    "color": "Peach",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.205",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/077_alda_peach.jpg"
  },
  {
    "id": 78,
    "collection": "Alda",
    "designNo": 205,
    "color": "Taupe",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.205",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/078_alda_taupe.jpg"
  },
  {
    "id": 79,
    "collection": "Alda",
    "designNo": 205,
    "color": "Nordic Forest",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.205",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/079_alda_nordic-forest.jpg"
  },
  {
    "id": 80,
    "collection": "Alda",
    "designNo": 205,
    "color": "Sage",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.205",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/080_alda_sage.jpg"
  },
  {
    "id": 81,
    "collection": "Structure",
    "designNo": 303,
    "color": "Dusty Sage",
    "quality": "Hand Knotted, 60 Knots",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "KE.303",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/081_structure_dusty-sage.jpg"
  },
  {
    "id": 82,
    "collection": "Solen",
    "designNo": 305,
    "color": "Walnut & Oat",
    "quality": "Hand Knotted, 80 Knots",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "KE.305",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/082_solen_walnut-and-oat.jpg"
  },
  {
    "id": 83,
    "collection": "Embla",
    "designNo": 301,
    "color": "Mocha & Oat",
    "quality": "Hand Knotted, 100 Knots",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "KE.301",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/083_embla_mocha-and-oat.jpg"
  },
  {
    "id": 84,
    "collection": "Meadow",
    "designNo": 106,
    "color": "Multicolor",
    "quality": "Flat Woven",
    "contents": "80% Wool 20% Linen",
    "stockRef": "JA.106",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/084_meadow_multicolor.jpg"
  },
  {
    "id": 85,
    "collection": "Meadow",
    "designNo": 106,
    "color": "Multicolor",
    "quality": "Flat Woven",
    "contents": "80% Wool 20% Linen",
    "stockRef": "JA.106",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/085_meadow_multicolor.jpg"
  },
  {
    "id": 86,
    "collection": "Eld",
    "designNo": 107,
    "color": "Multicolor",
    "quality": "Flat Woven",
    "contents": "80% Wool 20% Linen",
    "stockRef": "ID.107",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/086_eld_multicolor.jpg"
  },
  {
    "id": 87,
    "collection": "Shadow",
    "designNo": 108,
    "color": "Graphite Fade",
    "quality": "Flat Woven",
    "contents": "Wool",
    "stockRef": "MC.108",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/087_shadow_graphite-fade.jpg"
  },
  {
    "id": 88,
    "collection": "Field",
    "designNo": 212,
    "color": "Nordic Pine",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.212",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/088_field_nordic-pine.jpg"
  },
  {
    "id": 89,
    "collection": "Eye",
    "designNo": 109,
    "color": "Black & White",
    "quality": "Flat Woven",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "RA.109",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/089_eye_black-and-white.jpg"
  },
  {
    "id": 90,
    "collection": "Horizon",
    "designNo": 110,
    "color": "Deep Ocean & Ivory",
    "quality": "Flat Woven",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.110",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/090_horizon_deep-ocean-and-ivory.jpg"
  },
  {
    "id": 91,
    "collection": "Svala",
    "designNo": 111,
    "color": "Cobalt Blue",
    "quality": "Flat Woven",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "Jamal",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/091_svala_cobalt-blue.jpg"
  },
  {
    "id": 92,
    "collection": "Patch Triangle",
    "designNo": 501,
    "color": "Mix",
    "quality": "Stitched",
    "contents": "Leather",
    "stockRef": "ID.501",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/092_patch-triangle_mix.jpg"
  },
  {
    "id": 93,
    "collection": "Patch Diamond",
    "designNo": 502,
    "color": "Mix",
    "quality": "Stitched",
    "contents": "Leather",
    "stockRef": "ID.502",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/093_patch-diamond_mix.jpg"
  },
  {
    "id": 94,
    "collection": "Patch Chevron",
    "designNo": 503,
    "color": "Charcoal & Ivory",
    "quality": "Stitched",
    "contents": "Leather",
    "stockRef": "ID.503",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/094_patch-chevron_charcoal-and-ivory.jpg"
  },
  {
    "id": 95,
    "collection": "Patch Brick",
    "designNo": 504,
    "color": "Natural",
    "quality": "Stitched",
    "contents": "Leather",
    "stockRef": "ID.504",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/095_patch-brick_natural.jpg"
  },
  {
    "id": 96,
    "collection": "Patch Maze",
    "designNo": 506,
    "color": "Ivory & Brown",
    "quality": "Stitched",
    "contents": "Leather",
    "stockRef": "ID.505",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/096_patch-maze_ivory-and-brown.jpg"
  },
  {
    "id": 97,
    "collection": "Patch Linear",
    "designNo": 507,
    "color": "Greige",
    "quality": "Stitched",
    "contents": "Leather",
    "stockRef": "ID.506",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/097_patch-linear_greige.jpg"
  },
  {
    "id": 98,
    "collection": "Patch Grid",
    "designNo": 508,
    "color": "Gray & Ochre",
    "quality": "Stitched",
    "contents": "Leather",
    "stockRef": "ID.507",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/098_patch-grid_gray-and-ochre.jpg"
  },
  {
    "id": 99,
    "collection": "Flow",
    "designNo": 212,
    "color": "Dark Taupe",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "ID.212",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/099_flow_dark-taupe.jpg"
  },
  {
    "id": 100,
    "collection": "Flow",
    "designNo": 212,
    "color": "Ivory",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "IR.212",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/100_flow_ivory.jpg"
  },
  {
    "id": 101,
    "collection": "Frame",
    "designNo": 213,
    "color": "Camel",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "IR.213",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/101_frame_camel.jpg"
  },
  {
    "id": 102,
    "collection": "Frame",
    "designNo": 213,
    "color": "Gray",
    "quality": "Hand Loom",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "IR.213",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/102_frame_gray.jpg"
  },
  {
    "id": 103,
    "collection": "Blocks",
    "designNo": 402,
    "color": "Ivory",
    "quality": "Hand Tufted",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "JY.402",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/103_blocks_ivory.jpg"
  },
  {
    "id": 104,
    "collection": "Ray",
    "designNo": 306,
    "color": "Taupe & Ochre",
    "quality": "Hand Knotted, 80 Knots",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "IR.306",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/104_ray_taupe-and-ochre.jpg"
  },
  {
    "id": 105,
    "collection": "Contour",
    "designNo": 307,
    "color": "Ivory & Silver",
    "quality": "Hand Knotted",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "SS.307",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/105_contour_ivory-and-silver.jpg"
  },
  {
    "id": 106,
    "collection": "Ridge",
    "designNo": 113,
    "color": "Rust & Ivory",
    "quality": "Flat Woven",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.113",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/106_ridge_rust-and-ivory.jpg"
  },
  {
    "id": 107,
    "collection": "Prism",
    "designNo": 114,
    "color": "Truffle Mix",
    "quality": "Flat Woven",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.114",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/107_prism_truffle-mix.jpg"
  },
  {
    "id": 108,
    "collection": "Step",
    "designNo": 308,
    "color": "Warm Taupe",
    "quality": "Hand Knotted, 80 Knots",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "IR.308",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/108_step_warm-taupe.jpg"
  },
  {
    "id": 109,
    "collection": "Halo",
    "designNo": 403,
    "color": "Ivory & Sand",
    "quality": "Hand Tufted",
    "contents": "Wool & Linen",
    "stockRef": "CL.403",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/109_halo_ivory-and-sand.jpg"
  },
  {
    "id": 110,
    "collection": "Mono",
    "designNo": 115,
    "color": "Burgundy",
    "quality": "Flat Woven",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.115",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/110_mono_burgundy.jpg"
  },
  {
    "id": 111,
    "collection": "Yrsa",
    "designNo": 215,
    "color": "Camel",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "IR.215",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/111_yrsa_camel.jpg"
  },
  {
    "id": 112,
    "collection": "Mira",
    "designNo": 216,
    "color": "Walnut",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "IR.216",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/112_mira_walnut.jpg"
  },
  {
    "id": 113,
    "collection": "Embla",
    "designNo": 217,
    "color": "Dark Plum",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "IR.217",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/113_embla_dark-plum.jpg"
  },
  {
    "id": 114,
    "collection": "Tora",
    "designNo": 218,
    "color": "Burgundy",
    "quality": "Hand Loom, Loop & Cut",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "IR.218",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/114_tora_burgundy.jpg"
  },
  {
    "id": 115,
    "collection": "Nora",
    "designNo": 404,
    "color": "Ivory & Brown",
    "quality": "Hand Tufted",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.404",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/115_nora_ivory-and-brown.jpg"
  },
  {
    "id": 116,
    "collection": "Disa",
    "designNo": 405,
    "color": "Crimson",
    "quality": "Hand Tufted",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.405",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/116_disa_crimson.jpg"
  },
  {
    "id": 117,
    "collection": "Disa",
    "designNo": 405,
    "color": "Khaki",
    "quality": "Hand Tufted",
    "contents": "80% Wool 20% Cotton",
    "stockRef": "CL.405",
    "madeIn": "Indian",
    "notes": "",
    "imageSrc": "/collection/All_New_Collection_img/117_disa_khaki.jpg"
  }
];

// The four display categories used across the site
export const COLLECTION_CATEGORIES = [
  "Hand Loom",
  "Flat weave",
  "Hand Knotted",
  "Hand Tufted",
] as const;

// Maps a raw `quality` value (inconsistent casing/wording in the data)
// to one of the four display categories.
export function getQualityCategory(quality: string): string {
  const q = quality.toLowerCase();
  if (q.includes("flat")) return "Flat weave";
  if (q.includes("nepal") || q.includes("knot")) return "Hand Knotted";
  if (q.includes("hand loom") || q.includes("dual weave")) return "Hand Loom";
  if (q.includes("tuft")) return "Hand Tufted";
  return "Other";
}
